const GET_QUEUE_LIST_FETCHING = 'GET_QUEUE_LIST_FETCHING'
const GET_QUEUE_LIST_FAILED = 'GET_QUEUE_LIST_FAILED'
const GET_QUEUE_LIST_FETCHED = 'GET_QUEUE_LIST_FETCHED'
const GET_QUEUE_LIST_UPDATING = 'GET_QUEUE_LIST_UPDATING'