export const AUTHENTICATION_REQUEST_PENDING = 'AUTHENTICATION_REQUEST_PENDING'
export const AUTHENTICATION_REQUEST_SUCCESS = 'AUTHENTICATION_REQUEST_SUCCESS'
export const AUTHENTICATION_REQUEST_FAILED = 'AUTHENTICATION_REQUEST_FAILED'

export const CHECK_USER_AUTHENTICATION = 'CHECK_USER_AUTHENTICATION'
export const LOGOUT_AUTHENTICATION = 'LOGOUT_AUTHENTICATION'
export const UNVERIFY_AUTHENTICATION = 'UNVERIFY_AUTHENTICATION'
